---
- name: ansible roles
  hosts: local
  vars_files:
    - vars/registry.yml
    - vars/ocp-build.yml
  tasks:
    - name: OCP install config
      include_role:
        name: ocp-install-build-config
